### ISSUE TITLE
Yarn Test Errors

### ISSUE THREAD

**Issue by goheesheng** [rmrk-team/rmrk-substrate#272]
Hi, i tried running yarn test but leads to this error. I have also reinstall node.js but to no avail

test@test:~/Desktop/rmrk-substrate$ cd tests && yarn test
yarn run v1.22.19
warning ../../package.json: No license field
$ mocha --timeout 9999999 -r ts-node/register './src/*.test.ts'

✖ ERROR: Error: Cannot find module 'ts-node/register'
Require stack:
- /usr/lib/node_modules/mocha/lib/nodejs/esm-utils.js
- /usr/lib/node_modules/mocha/lib/mocha.js
- /usr/lib/node_modules/mocha/lib/cli/one-and-dones.js
- /usr/lib/node_modules/mocha/lib/cli/options.js
- /usr/lib/node_modules/mocha/bin/mocha.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at exports.requireOrImport (/usr/lib/node_modules/mocha/lib/nodejs/esm-utils.js:53:16)
    at async exports.handleRequires (/usr/lib/node_modules/mocha/lib/cli/run-helpers.js:94:28)
    at async /usr/lib/node_modules/mocha/lib/cli/run.js:349:25 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/mocha/lib/nodejs/esm-utils.js',
    '/usr/lib/node_modules/mocha/lib/mocha.js',
    '/usr/lib/node_modules/mocha/lib/cli/one-and-dones.js',
    '/usr/lib/node_modules/mocha/lib/cli/options.js',
    '/usr/lib/node_modules/mocha/bin/mocha.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ilionic** [comment]
Hi, did you install modules in tests folder? yarn install
Which nodejs version do you have?

**Comment by goheesheng** [comment]
Hi I tried using v18.13.0 and v19.5.0

**Comment by ilionic** [comment]
Did you install dependencies? `yarn install`
